README.md
build.sbt
src/main/scala/com/gu/scanamo/DynamoResultStream.scala
src/main/scala/com/gu/scanamo/Scanamo.scala
src/main/scala/com/gu/scanamo/ScanamoAsync.scala
src/main/scala/com/gu/scanamo/ScanamoFree.scala
src/main/scala/com/gu/scanamo/ScanamoOpsA.scala
src/main/scala/com/gu/scanamo/package.scala
src/test/scala/com/gu/scanamo/LocalDynamoDB.scala
src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala

This adds `ScanamoAsync` which has the same interface as `Scanamo` except that it requires an `ExecutionContext` in scope and returns a `Future`.
I've avoided duplication by abstracting over the precise execution behaviour using the [Free Monad](http://typelevel.org/cats/tut/freemonad.html). This also means that if you want a purely functional interface you can use the Free structure directly and push its interpretation to the end of the world.

Support async interaction with Dynamo

---

README.md
src/main/scala/com/gu/scanamo/DynamoFormat.scala
src/main/scala/com/gu/scanamo/DynamoReadError.scala

The common case is that there is some potential exception thrown when converting back from what was stored in Dynamo

Provide a simplified means of creating a DynamoFormat

---

README.md
src/main/scala/com/gu/scanamo/DynamoFormat.scala
src/main/scala/com/gu/scanamo/DynamoReadError.scala
src/main/scala/com/gu/scanamo/DynamoResultStream.scala
src/main/scala/com/gu/scanamo/Scanamo.scala
src/main/scala/com/gu/scanamo/ScanamoAsync.scala
src/main/scala/com/gu/scanamo/ScanamoFree.scala
src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala

Whilst we want to accumulate errors when hydrating case classes, we don't need this behaviour generally. Xor is slightly more familiar and we don't need a list of errors.

Use Xor instead of Validated in the main interface

---

src/test/scala/com/gu/scanamo/LocalDynamoDB.scala

Previously one failing test could cause lots of spurious failures

Always delete tables created during tests

---

build.sbt
src/main/scala/com/gu/scanamo/DynamoFormat.scala

Also remove test that depended on the order in `Map`'s toString, which isn't determined and for some reason changed on the upgrade.

Upgrade to cats 0.6.0

---

README.md
src/main/scala/com/gu/scanamo/Scanamo.scala
src/main/scala/com/gu/scanamo/ScanamoAsync.scala
src/main/scala/com/gu/scanamo/ScanamoFree.scala
src/main/scala/com/gu/scanamo/ScanamoRequest.scala
src/main/scala/com/gu/scanamo/Table.scala
src/main/scala/com/gu/scanamo/package.scala
src/main/scala/com/gu/scanamo/query/UniqueKeyCondition.scala
src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala
src/test/scala/com/gu/scanamo/ScanamoTest.scala

As noted in #50, DynamoDB assumes that bulk operations are performed on a Set. This doesn't ensure the set is of the form expected by DynamoDB, i.e. it doesn't ensure the hash/range key combination are unique, but I think it better conveys the intent.
cc @lindseydew @emma-p

Use Sets for bulk operations

---

src/main/scala/com/gu/scanamo/DerivedDynamoFormat.scala
src/main/scala/com/gu/scanamo/DynamoFormat.scala

DynamoFormat is getting big enough that it's awkward to work with and this behaviour is fairly distinct and already in it's own trait.

Move DerivedDynamoFormat to it's own file

---

src/main/scala/com/gu/scanamo/Scanamo.scala
src/main/scala/com/gu/scanamo/Table.scala

Added to Table, Index and their equivalents with a limit.  This is not strictly necessary as if you import the Scanamo syntax it will augment the classes appropriately, but they don't show up in Scaladoc and people were confused, so this adds them explicitly.

Add explicit query and scan methods

---

build.sbt
project/build.properties
src/main/scala/com/gu/scanamo/DerivedDynamoFormat.scala
src/main/scala/com/gu/scanamo/DynamoFormat.scala
src/main/scala/com/gu/scanamo/ScanamoAsync.scala
src/main/scala/com/gu/scanamo/ScanamoFree.scala
src/main/scala/com/gu/scanamo/error/DynamoReadError.scala
src/main/scala/com/gu/scanamo/update/UpdateExpression.scala

This updates the library to the Cats 0.7.0 snapshot, and shouldn't be merged until 0.7.0 is published. It also depends on [this Cats change](https://github.com/typelevel/cats/pull/1261), which is merged but not yet in the snapshot, so you'll have to publish the snapshot locally if you want to run the tests right now (they do pass if you do that).
I've also changed the cats dependency from `cats` to `cats-free`, since the `cats` module is [only meant to be a pedagogical convenience](https://github.com/typelevel/cats/issues/1181#issuecomment-231589592) (it pulls in test dependencies, etc.), and shouldn't be used in production.

Update to Cats 0.7.0

---

README.md
src/main/scala/com/gu/scanamo/package.scala
src/main/scala/com/gu/scanamo/update/UpdateExpression.scala

Note that this is different from the already implemented `DELETE`.
* `DELETE` is for deleting a given element from a Set attribute
* `REMOVE` is for removing an attribute from an item

Add REMOVE support to the update API

---

build.sbt
src/main/scala/com/gu/scanamo/DerivedDynamoFormat.scala

Add a universal macro at the bottom of the priority tree that reports the specific missing DynamoFormat, not just the top-level case class.
This is a REPL session showing the behaviour:
Previously you would just get that last line.

Provide better errors when can't derive a DynamoFormat

---

src/main/scala/com/gu/scanamo/DynamoFormat.scala

This is complicated by the fact that the Java client's API returns a boxed Boolean which is `null` if no NULL value is set. Using an explicit `Boolean.unbox`, so that `null` evaluates to `false`is the least clumsy workaround I can find for this.

Read DynamoDB NULL as None

---

src/main/scala/com/gu/scanamo/DynamoFormat.scala

This is a purely selfish PR. Given:
```
case class RoleId(value: String) extends AnyVal
```
it means I can write:
```
implicit val dynamoFormat: DynamoFormat[RoleId] =
DynamoFormat.map[RoleId, String](RoleId.apply)(_.value)
```
instead of:
```
implicit val dynamoFormat: DynamoFormat[RoleId] =
DynamoFormat.xmap[RoleId, String](value => Xor.right(RoleId(value)))(_.value)
```

Add a map method to DynamoFormat

---

.travis.yml
CHANGES.md
README.md
build.sbt
src/main/scala/com/gu/scanamo/Scanamo.scala
src/main/scala/com/gu/scanamo/ScanamoAsync.scala
src/main/scala/com/gu/scanamo/ScanamoFree.scala
src/main/scala/com/gu/scanamo/Table.scala
src/main/scala/com/gu/scanamo/error/DynamoReadError.scala
src/main/scala/com/gu/scanamo/ops/ScanamoInterpreters.scala
src/main/scala/com/gu/scanamo/query/ConditionExpression.scala

This an attempt to address #61 and I'd love to hear whether this is actually a solution or not.
My presumption is that it's much more likely that someone will be interested in the state after the update than before, so this changes the default behaviour to return that and uses the `DynamoFormat` to then transform that back into the case class associated with the table.
My belief is that this will address most use cases without significantly complicating the interface, but can be convinced that's not the case.

Return the new value after an update

---

README.md
build.sbt
src/main/scala/com/gu/scanamo/DerivedDynamoFormat.scala
src/main/scala/com/gu/scanamo/DynamoFormat.scala
src/main/scala/com/gu/scanamo/DynamoResultStream.scala
src/main/scala/com/gu/scanamo/Scanamo.scala
src/main/scala/com/gu/scanamo/ScanamoAsync.scala
src/main/scala/com/gu/scanamo/ScanamoFree.scala
src/main/scala/com/gu/scanamo/Table.scala
src/main/scala/com/gu/scanamo/ops/ScanamoInterpreters.scala
src/main/scala/com/gu/scanamo/ops/ScanamoOpsA.scala
src/main/scala/com/gu/scanamo/query/ConditionExpression.scala
src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala

With `Either` becoming left-biased in Scala 2.12, cats is moving away from `Xor`. This is a very literal replacement to try and stay ahead of that change.
As part of a future change, I'd like to represent more errors as values, but this change doesn't address that.

`Xor` -> `Either`

---

src/main/scala/com/gu/scanamo/Scanamo.scala
src/main/scala/com/gu/scanamo/ScanamoAsync.scala
src/main/scala/com/gu/scanamo/ScanamoFree.scala
src/main/scala/com/gu/scanamo/Table.scala
src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala
src/test/scala/com/gu/scanamo/ScanamoTest.scala

This builds on #71 to add support consistent Scan/Query, as  I wanted to see what that looked like.
It would be good to add some tests which actually require consistency to verify that works as desired.

Consistent Get/Scan/Query

---

src/main/tut/batch-operations.md

`toOption` is only in stdlib in 2.12, need cats syntax for example to compile on 2.11

Fix documentation example for 2.11

---

src/main/scala/com/gu/scanamo/Table.scala
src/main/scala/com/gu/scanamo/update/UpdateExpression.scala

This avoids the following error: `The provided expression refers to an attribute that does not exist in the item`

Create list if it does not exist when appending/prepending

---

src/main/scala/com/gu/scanamo/DynamoFormat.scala

This seems a very common use case, at least at the Guardian, and this seems a reasonable default.

Add default format for UUID

---

src/main/scala/com/gu/scanamo/DerivedDynamoFormat.scala
src/main/scala/com/gu/scanamo/DynamoFormat.scala

Coproducts are encoded as a map with one field, whose key is the type hint.
e.g. given
```scala
sealed trait Animal
case class Cat(name: String, legs: Int) extends Animal
val cat = Cat("Eric", 4)
```
`cat` would be encoded in Dynamo as (using jsony syntax) `{ "Cat": { "name": "Eric", "legs": 4 } }`
I feel like there must be a good reason why @philwills decided not to implement this until now, but I think it is pretty useful. For example it means you can encode enumerations using a sealed trait + case objects, which is a very common thing to do, without having to write a boilerplate-y custom `DynamoFormat`.

Support derivation of coproducts

---

src/main/scala/com/gu/scanamo/Scanamo.scala
src/main/scala/com/gu/scanamo/ScanamoAsync.scala
src/main/scala/com/gu/scanamo/ScanamoFree.scala
src/main/scala/com/gu/scanamo/Table.scala
src/main/scala/com/gu/scanamo/package.scala
src/main/scala/com/gu/scanamo/query/ConditionExpression.scala
src/main/scala/com/gu/scanamo/update/UpdateExpression.scala
src/main/tut/updating.md

Fixes #68 by moving to a more direct encoding of `UpdateExpression`.
I could have sworn I tried this a couple of months ago and ran into problems, but this attempt passes all the existing tests without intervention.

Dynamic updates

---

src/main/scala/com/gu/scanamo/package.scala
src/main/scala/com/gu/scanamo/update/UpdateExpression.scala
src/test/scala/com/gu/scanamo/update/UpdateExpressionTest.scala

Previously the repeated search and replace of a string could lead to multiple parameters having the same placeholder in the expression string.

Fix bug when many updates and'd together

---

src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala

Even a `getWithConsistency` can fail if the request is made before the request for the `put` which can happen when using async requests.

Prevent intermittent test failures

---

src/main/scala/com/gu/scanamo/DynamoResultStream.scala
src/main/scala/com/gu/scanamo/ScanamoFree.scala
src/main/scala/com/gu/scanamo/Table.scala
src/main/scala/com/gu/scanamo/ops/ScanamoInterpreters.scala
src/main/scala/com/gu/scanamo/ops/ScanamoOpsA.scala
src/main/scala/com/gu/scanamo/package.scala
src/main/scala/com/gu/scanamo/query/ConditionExpression.scala
src/main/scala/com/gu/scanamo/request/ScanamoRequest.scala
src/test/scala/com/gu/scanamo/ScanamoFreeTest.scala

Support filtering of `Scan` and `Query` results in DynamoDB before they are returned to the client.
Addresses #42

Filtering of Scan and Query

---

src/main/scala/com/gu/scanamo/Table.scala
src/main/scala/com/gu/scanamo/ops/ScanamoInterpreters.scala

DynamoDB throws an error if you provide an empty Map as the attribute values.

Support filtering by attribute existence on scans

---

src/main/scala/com/gu/scanamo/Table.scala
src/main/scala/com/gu/scanamo/query/QueryableKeyCondition.scala

This is relevant for indexes where there may be many results for the same hash and range key.
This addresses #113  and #120 
Ideally, I'd like this to only compile for queries on an index, not directly on a table, but that would involve quite a lot more type gymnastics and I'm not sure there's enough value for that to be worth it.

Allow querying on an exact hash and range key

---

build.sbt
project/plugins.sbt
src/main/scala/com/gu/scanamo/DynamoFormat.scala
src/main/scala/com/gu/scanamo/ScanamoFree.scala

To achieve this change `traverseU` was changed to `traverse`. 
Updated to scala 2.11.11 so partial unification was available.

Cats 1.0.0-MF changes

---

src/main/scala/com/gu/scanamo/DerivedDynamoFormat.scala
src/main/scala/com/gu/scanamo/DynamoFormat.scala
src/test/scala/com/gu/scanamo/EnumDynamoFormatTest.scala

`new AttributeValue().withM(Map.empty[String, AttributeValue].asJava)`
is a base to build from, but cannot be written to Dynamo, so should
never be derived as the serialisation form for a type.
This moves the problems with #138 to compile time, rather than run time.

Don't allow an empty map to be derived as a DynamoFormat

---

build.sbt

They aren't supported and error on 2.11

Only use funky scalac lint options on 2.12

---

build.sbt

I quite often dip into the console to validate things and without this, it becomes pretty unusable.

Disable unused warnings for the console

---

build.sbt
docs/src/main/tut/asynchronous.md

Make the `docs` subproject depend on `scanamo` and `alpakka` subproject as we need Akka's `ActorSystem` and `ActorMaterializer` as they are dependencies needed for the Alpakka client to function.
**Note:** Don't bring in test files from alpakka as they interfere with scanamo's test files causing the Local DynamoDB to point to the wrong port.

Update documentation for the asynchronous interpreters

---

scanamo/src/main/scala/com/gu/scanamo/Table.scala
scanamo/src/main/scala/com/gu/scanamo/query/ConditionExpression.scala

Fixes remaining issue in #136. Slight addition to #156, which adds an implicit conversion from `(AttributeName, V)` to `ConditionExpression`, necessary to support nested fields. Not the prettiest code, but I could not find a solution to replace `Symbol, V)` conversion completely.

Equals condition support for nested attributes

---

alpakka/src/main/scala/com/gu/scanamo/ScanamoAlpakka.scala
alpakka/src/test/scala/com/gu/scanamo/ScanamoAlpakkaSpec.scala
scanamo/src/main/scala/com/gu/scanamo/Scanamo.scala
scanamo/src/main/scala/com/gu/scanamo/ScanamoAsync.scala
scanamo/src/main/scala/com/gu/scanamo/ScanamoFree.scala
scanamo/src/main/scala/com/gu/scanamo/Table.scala
scanamo/src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala

Implements [consistent reads](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadConsistency.html) for the `getAll` operation (`getAllWithConistency`).
Note: the tests appear to only test that the `WithConsistency` methods function correctly, and don't directly test that the `KeysAndAttributes.consistentRead` field is set. This could be tested using a test interpreter which would capture the resultant `BatchGetItemRequest` and test that `consistentRead` is set.

Implement get all with consistent reads

---

CONTRIBUTING.md
docs/src/main/tut/conditional-operations.md
docs/src/main/tut/filters.md
docs/src/main/tut/operations.md

Many links to the scaladocs were linking to a url with a /scanamo
prefix. However, the main documentation is just hosted at /, causing
broken links.
Ran `grep -r "/scanamo"` to ensure I picked up all the links and built the docs to make sure the links worked now.

Fix broken documentation links

---

scanamo/src/main/scala/com/gu/scanamo/Table.scala
scanamo/src/main/scala/com/gu/scanamo/package.scala
scanamo/src/main/scala/com/gu/scanamo/update/UpdateExpression.scala
scanamo/src/test/scala/com/gu/scanamo/update/UpdateExpressionTest.scala

Adds two new functions: `appendList` and `prependList`. Each takes
a list argument and appends or prepends it to an existing value at
the specified attribute name.
The previous methods, `append` and `prepend`, are unchanged: they
take a value, cast it to a list of a single element, and then
append/prepend it. This does not allow for list concatenation;
appending a list would result in a nested list, thus likely causing
any custom deserialization that expected a flat list for the updated
attribute to fail.
I messed around with ways to allow the existing `append` to take either a list or a single argument with varargs and things like that but couldn't get anything working. Since the argument is a tuple I wasn't able to do something clever like overload `def append[V: …

Allow append/prepend of list values

---

build.sbt
docs/src/main/tut/dynamo-format.md
refined/src/main/scala/com/gu/scanamo/refined/package.scala
refined/src/test/scala/com/gu/scanamo/refined/RefinedDynamoFormatSpec.scala

Hi all, hope you find this interesting.
At work we use refined types in some projects so we end up writing wiring (integration?) with other libraries that do not support it. Most of the time the code is as trivial as in this case, so I took the liberty of adding a module to the project to support them so everyone else can also profit from it.

Add a module to support refined types

---

docs/src/main/tut/dynamo-format.md

Because it is useful to understand the implementation before attempting
to use this awesome feature (microsite tested locally).

Add derived format documentation

---

testkit/src/main/scala/com/gu/scanamo/LocalDynamoDB.scala

There seems to be tables not being properly deleted in tests, perhaps because of concurrency issues. Trying the brute force first.

Delete table if exists

---

alpakka/src/test/scala/com/gu/scanamo/ScanamoAlpakkaSpec.scala
cats/src/test/scala/com/gu/scanamo/ScanamoCatsSpec.scala
scalaz/src/test/scala/com/gu/scanamo/ScanamoScalazSpec.scala
scanamo/src/main/scala/com/gu/scanamo/Scanamo.scala
scanamo/src/main/scala/com/gu/scanamo/SecondaryIndex.scala
scanamo/src/main/scala/com/gu/scanamo/Table.scala
scanamo/src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala
scanamo/src/test/scala/com/gu/scanamo/ScanamoTest.scala
scanamo/src/test/scala/com/gu/scanamo/update/UpdateExpressionTest.scala
testkit/src/main/scala/com/gu/scanamo/LocalDynamoDB.scala

Coming up with table names is an annoyance in tests, only exacerbated by the fact that there may be some race condition lurking around (explaining the "cannot create preexisting table" exceptions occurring on Travis but not locally).
This PR introduces three new APIs in the `LocalDynamoDB` facility:
- `withRandomTable`
- `withRandomTableWithSecondaryIndex`
- `usingRandomTable`
They work exactly the same as their non-random counterparts, only that the thunk takes the table name as input.

Random table API in testkit

---

scanamo/src/main/scala/com/gu/scanamo/Table.scala
scanamo/src/main/scala/com/gu/scanamo/query/UniqueKeyCondition.scala

Adds the ability to paginate using the `Table` API, as methods other than `exec` on `Scanamo*` will eventually be [deprecated](#146).
At the moment, it requires the addition of two new APIs on `TableWithOptions`, namely `scanWithLastKey` and `queryWithLastKey`, so that the result can contain the last pagination key if there is one. This is not ideal, augmenting the surface API introduces new opportunities for bugs to creep in. What we want are "all-powerful" scan/query operations, let's call them `scan0`/`query0` and all the other variants piggyback on them with ad hoc defaults.
Another issue I need to figure out is the asymmetry between the input key (a `UniqueKey[_]`) and the output key (a `java.util.Map[String, AttributeValue]`). I have added enriched `UniqueKeyCondition` with a …

Add `Table.queryFrom` and `Table.scanFrom`

---

build.sbt
cats/src/main/scala/com/gu/scanamo/ops/CatsInterpreter.scala
formats/src/main/scala/com/gu/scanamo/DerivedDynamoFormat.scala
project/plugins.sbt
scalaz/src/main/scala/com/gu/scanamo/ScanamoScalaz.scala
scanamo/src/main/scala/com/gu/scanamo/Scanamo.scala
scanamo/src/main/scala/com/gu/scanamo/ScanamoFree.scala
scanamo/src/main/scala/com/gu/scanamo/SecondaryIndex.scala
scanamo/src/main/scala/com/gu/scanamo/query/ConditionExpression.scala

There's a weird conflict that did not appear when I ran it locally (neither when I raised the PR 🤔 ), where v1.5 of scalafmt depends on an older version of scalameta, while sbt-doctest uses a more recent one. This fixes the issue. There is one open regression with this version of scalafmt but I don't think it affects our project, so I would say it's not much of a risk.
Plus it catches a few uses cases that were not caught and the code looks nicer ✨

Upgrade scalafmt to RC

---

build.sbt
formats/src/main/scala/com/gu/scanamo/DynamoFormat.scala
version.sbt

- scalacheck has some problems in forked mode that have been fixed in this new version
- `sonatypeReleaseAll` sends _all_ published package of the com.gu organisation to maven, as opposed to `sonatypeRelease`
- in scala 2.11, the AWS SDK returns `null` when calling `av.isNULL` on an attribute value that is not null
- updated scala for security and performance improvements

Fix a few release issues

---

cats/src/main/scala/com/gu/scanamo/ScanamoCats.scala
cats/src/main/scala/com/gu/scanamo/ops/CatsInterpreter.scala

Hi,
This PR just find/replaces `Effect` with `Async` as there are no uses of `runAsync` or `toIO` and I want to use a `StateT` as my effect type, which can only have an `Async` instance.
Hope this looks okay, let me know if you'd like any changes (or if I've missed something about `Effect`)
... actually it looks like I'm going in the wrong direction by trying to use `StateT`, but I guess this PR still has relevance. Looks like the tests just failed due to a timeout but I can't rerun them :(

Use Async rather than Effect in cats-effect

---

README.md
alpakka/src/test/scala/com/gu/scanamo/ScanamoAlpakkaSpec.scala
cats/src/test/scala/com/gu/scanamo/ScanamoCatsSpec.scala
docs/src/main/tut/asynchronous.md
docs/src/main/tut/batch-operations.md
docs/src/main/tut/conditional-operations.md
docs/src/main/tut/dynamo-format.md
docs/src/main/tut/filters.md
docs/src/main/tut/index.md
docs/src/main/tut/operations.md
docs/src/main/tut/using-indexes.md
formats/src/main/scala/com/gu/scanamo/Derivation/SemiAutoDerivation.scala
formats/src/main/scala/com/gu/scanamo/DerivedDynamoFormat.scala
formats/src/main/scala/com/gu/scanamo/DynamoFormat.scala
formats/src/main/scala/com/gu/scanamo/EnumerationDynamoFormat.scala
formats/src/main/scala/com/gu/scanamo/auto.scala
formats/src/main/scala/com/gu/scanamo/export/Exported.scala
formats/src/main/scala/com/gu/scanamo/semiauto.scala
formats/src/test/scala/com/gu/scanamo/Derivation/SemiAutoDerivationTest.scala
formats/src/test/scala/com/gu/scanamo/DynamoFormatTest.scala
scalaz-zio/src/test/scala/com/gu/scanamo/ScanamoZioSpec.scala
scalaz/src/test/scala/com/gu/scanamo/ScanamoScalazSpec.scala
scanamo/src/main/scala/com/gu/scanamo/Scanamo.scala
scanamo/src/main/scala/com/gu/scanamo/ScanamoFree.scala
scanamo/src/main/scala/com/gu/scanamo/SecondaryIndex.scala
scanamo/src/main/scala/com/gu/scanamo/Table.scala
scanamo/src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala
scanamo/src/test/scala/com/gu/scanamo/ScanamoTest.scala

- Auto derivation of case classes now requires `import com.gu.scanamo.auto._`
and doesn't come automatically as soon as DynamoFormat is in scope
- Adding semi-automatic derivation via `deriveDynamoFormat[A]` helper method
Closes #201

Add automatic and semi-automatic derivation of DynamoFormat

---

formats/src/main/scala/org/scanamo/DynamoFormat.scala
scanamo/src/test/scala/org/scanamo/update/UpdateExpressionTest.scala

Fixes #366 
That DynamoDB won't accept empty strings is a long-standing pain in the ass. As of now, we've been encoding strings without taking care of it, but the result is this behaviour bubbles up into user-land code where people must come up with handling mechanisms. It seems we can take care of this ourselves, by encoding empty strings as nulls.
To make matters even worse, when marshalling an object, if a key has a null value, it will be stripped off in DynamoDB. As a result, we must make sure that missing properties of type `String` are properly decoded into the empty string: this is what the `DynanoFormat[String]#default` value is for.

Write empty strings as null

---

CONTRIBUTING.md

I noticed while trying to run tests that a local dynamodb is required to be running at port 8042. I added this information to CONTRIBUTING.md, so that future contributers won't waste time on this. Cheers :)

Add startDynamodbLocal sbt task information to CONTRIBUTING.md

---

docs/src/main/tut/conditional-operations.md
docs/src/main/tut/dynamo-format.md
docs/src/main/tut/filters.md
docs/src/main/tut/operations.md

It looks like package structure was changed at some point but links on doc pages weren't adjusted.

Fix links in doc pages

---

scanamo/src/main/scala/org/scanamo/ScanamoFree.scala
scanamo/src/main/scala/org/scanamo/Table.scala
scanamo/src/main/scala/org/scanamo/ops/ScanamoInterpreters.scala
scanamo/src/main/scala/org/scanamo/query/ConditionExpression.scala

- I've noticed the `Option[RequestCondition]` was never used in instances of `ConditionExpression`, so removing that
- also got rid of the `xxxWithConsistency` calls, replaced with a simple boolean in `ScanamoFree.xxx`
- the max batch size for `BatchGetItem` is 100, not 25
- avoids extra allocations when we get closer to the metal. I'd like to develop a habit of directly using the Java structures when we interact with the dynamo api instead of relying on java converters

A few cleanups

---

project/plugins.sbt

As highlighted on this comment:
https://github.com/scanamo/scanamo/pull/422#issuecomment-498638872
sbt-doctest 0.9.2 is causing an issue on windows which is this exception:
`
[error] org.scalameta.invariants.InvariantFailedException: invariant failed: [error] when verifying ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)).==('\"') [error] found that ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)) is not equal to '\"' [error] where ScalametaTokenizer = scala.meta.internal.tokenizers.ScalametaTokenizer@3b827a9e [error] at org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:15) [error] at scala.meta.internal.tokenizers.ScalametaTokenizer.emitContents$1(ScalametaTokenizer.scala:222) [error] at …

update doctest version since it's causing exception on windows

---

README.md
alpakka/src/test/scala/org/scanamo/ScanamoAlpakkaSpec.scala
cats/src/test/scala/org/scanamo/ScanamoCatsSpec.scala
docs/src/main/tut/asynchronous.md
docs/src/main/tut/batch-operations.md
docs/src/main/tut/conditional-operations.md
docs/src/main/tut/dynamo-format.md
docs/src/main/tut/filters.md
docs/src/main/tut/index.md
docs/src/main/tut/operations.md
docs/src/main/tut/using-indexes.md
formats/src/main/scala/org/scanamo/DerivedDynamoFormat.scala
formats/src/test/scala/org/scanamo/DynamoFormatTest.scala
scalaz-zio/src/test/scala/org/scanamo/ScanamoZioSpec.scala
scalaz/src/test/scala/org/scanamo/ScanamoScalazSpec.scala
scanamo/src/main/scala/org/scanamo/ScanamoSync.scala
scanamo/src/main/scala/org/scanamo/SecondaryIndex.scala
scanamo/src/main/scala/org/scanamo/Table.scala
scanamo/src/main/scala/org/scanamo/package.scala
scanamo/src/main/scala/org/scanamo/query/AttributeName.scala
scanamo/src/main/scala/org/scanamo/query/ConditionExpression.scala
scanamo/src/main/scala/org/scanamo/query/DynamoKeyCondition.scala
scanamo/src/main/scala/org/scanamo/query/QueryableKeyCondition.scala
scanamo/src/main/scala/org/scanamo/query/UniqueKeyCondition.scala
scanamo/src/main/scala/org/scanamo/update/UpdateExpression.scala
scanamo/src/test/scala/org/scanamo/ScanamoAsyncTest.scala
scanamo/src/test/scala/org/scanamo/ScanamoTest.scala
scanamo/src/test/scala/org/scanamo/update/UpdateExpressionTest.scala
testkit/src/main/scala/org/scanamo/LocalDynamoDB.scala

Close #390 
Symbols don't get a fancy syntactic treatment in Scala 2.13, as that notation doesn't generally play ball in IDEs. It was the only reason to use symbols in the first place, but even in real life when attribute names are not static, they're awkward to work with.
Note that 2.13 supports singleton types, in a future version of the API we may want to leverage that somehow.

Replace `Symbol` with `String`

---

alpakka/src/main/scala/org/scanamo/ScanamoAlpakka.scala
build.sbt
cats/src/main/scala/org/scanamo/ScanamoCats.scala
cats/src/test/scala/org/scanamo/ScanamoCatsSpec.scala
scalaz-zio/src/main/scala/org/scanamo/ScanamoZio.scala
scalaz-zio/src/main/scala/org/scanamo/ops/ZioInterpreter.scala
scalaz-zio/src/test/scala/org/scanamo/ScanamoZioSpec.scala
scalaz/src/main/scala/org/scanamo/ScanamoScalaz.scala
scanamo/src/main/scala/org/scanamo/DynamoResultStream.scala
scanamo/src/main/scala/org/scanamo/ScanamoAsync.scala
scanamo/src/main/scala/org/scanamo/ScanamoFree.scala
scanamo/src/main/scala/org/scanamo/ScanamoSync.scala
scanamo/src/main/scala/org/scanamo/SecondaryIndex.scala
scanamo/src/main/scala/org/scanamo/Table.scala
scanamo/src/main/scala/org/scanamo/ops/package.scala
scanamo/src/test/scala/org/scanamo/ScanamoAsyncTest.scala
scanamo/src/test/scala/org/scanamo/ScanamoTest.scala

Closes #275 
Closes #181 
Adds `[scan|query]To` and `[scan|query]toPaged` that thread in an effect type with monoid properties (`Alternative <: Applicative with MonoidK`). Actually we need a stronger constraint, `MonadPlus`, as this is [required in the interpreter](https://github.com/scanamo/scanamo/pull/432), but that class is missing in cats.
- ~~rewrite `scan` and `query` with `[scan|query]To`~~

Allow streaming in constant space

---

alpakka/src/main/scala/org/scanamo/ScanamoAlpakka.scala
alpakka/src/main/scala/org/scanamo/ops/retrypolicy/RetryPolicy.scala
alpakka/src/main/scala/org/scanamo/ops/retrypolicy/WithRetry.scala
alpakka/src/test/scala/org/scanamo/RetryPolicySpec.scala

Closes #448 
Also steals tests from the ticket.
Fixes:
- Max bottoms out at 0 and never goes below
- switch `Duration` for `FiniteDuration` (`Never ~ Duration.Inf`)
- Fixes exponential delay calculation
- adds constructors to guarantee correctness
- proper introduction of a delay in the stream algebra

RetryPolicy fixes

---

formats/src/main/scala/org/scanamo/DynamoFormat.scala

This allows for a Generic Scala `Set` to be interpreted by the program. 
Previously Sets of numbers and strings were accepted, but not Sets of custom objects. Provided the items are in a DynamoFormat, this can now be done.

Add generic set to Dynamo Formats

---

zio/src/main/scala/org/scanamo/ScanamoZio.scala
zio/src/test/scala/org/scanamo/ScanamoZioSpec.scala

They are [now provided](https://github.com/zio/interop-cats/pull/67) by the interop layer and properly battle-tested for correctness (which wasn;'t the case here 😅 ).

Use zio stream provided instances

---

build.sbt

This was conflicting with a different version of scalatest, when depending on scanamo.

Only depend on scalatestplus-scalacheck in Test

---

alpakka/src/main/scala/org/scanamo/ScanamoAlpakka.scala
alpakka/src/main/scala/org/scanamo/ops/AlpakkaInterpreter.scala
alpakka/src/main/scala/org/scanamo/ops/retrypolicy/RetryPolicy.scala
alpakka/src/main/scala/org/scanamo/ops/retrypolicy/WithRetry.scala
alpakka/src/test/scala/org/scanamo/RetryPolicySpec.scala

Previously it was hardcoded what `Throwable` should be retried (see
`WithRetry` trait).  However we are currently experiencing serious
issues with 500 from DynamoDB that we (in our case) would like to
retry.
With this pr, we pass a predicate `Throwable => Boolean` from
`ScanamoAlpakka` down to the `AlpakkaInterpreter` to implement the new
abstract `retryable` method from `WithRetry`.
By default, we use the same retry behavior as before, see
`ScanamoAlpakka.defaultRetryableCheck`
What do you think?

Allow customization of retryable exceptions

---

scanamo/src/main/scala/org/scanamo/DynamoFormat.scala
scanamo/src/test/scala/org/scanamo/generic/SemiAutoDerivationTest.scala

Some methods did not have return type
annotations (e.g. DynamoFormat.xmap) which meant that something
inference / tooltips would show a ugly type instead.  Fixed by adding
the annotations.

Annotate return types

---

joda/src/main/scala/org/scanamo/joda/JodaFormats.scala
scanamo/src/main/scala/org/scanamo/DynamoFormat.scala

Adds the `xmap`/`coercedXmap`/`iso` method to all `DynamoFormat`, being essentially a
shortcut to the static `DynamoFormat.{xmap,coercedXmap,iso}`
Besides convenience, the type-inference is also much better.

Add DynamoFormat#{xmap,coercedXmap,iso}

---

.scala-steward.conf

Unignore SDK updates, it seems they do break the underlying format from time to time, which is probably why #593 happened.

AWS SDK changes are too important

---

scanamo/src/main/scala/org/scanamo/DynamoValue.scala

It is useful for debugging to be able to magic up a table that pulls the
raw data down without trying to decode it.

Add DynamoFormat for DynamoValue

---

CONTRIBUTING.md

This release process was introduced in #280, this PR just documents it.

Update instructions on releasing to Maven Central

---

.gitignore
scanamo/src/main/scala/org/scanamo/DynamoValue.scala
scanamo/src/test/scala/org/scanamo/DynamoValueTest.scala

Fixes #959 
Looks like the SDK is creating a read-only bytebuffer.

Create copy of bytes from SDK

---

scripts/publishMicrosite.sh

The code snippets in the microsite need DynamodbLocal to be running to work.

Run DynamodbLocal while microsite is building

---

cats/src/test/scala/org/scanamo/ScanamoCatsSpec.scala
scanamo/src/main/scala/org/scanamo/DynamoResultStream.scala

I noticed a bug with `scanPaginatedM` namely dynamo returns an empty object as last key when the result size is less than the limit, i.e. there are no more pages.  However `ScanResponseStream` doesn't recognize this and still try to use the empty object as the next start key causing a 
```
software.amazon.awssdk.services.dynamodb.model.DynamoDbException: Exclusive Start Key must have same size as table's key schema
```
This PR changed one of the tests to expose this error and fixed the bug by filtering out empty last key.

Fix a bug in `ScanResponseStream`

---

build.sbt
cats/src/main/scala/org/scanamo/ops/CatsInterpreter.scala
cats/src/test/scala/org/scanamo/ScanamoCatsSpec.scala

The new, stricter eviction logic in sbt v1.5 (see https://github.com/sbt/sbt/pull/6221) spotted that the versions of `cats-effect` used by Scanamo were suspected to be binary incompatible:
```
[error] (zio / update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.typelevel:cats-effect_2.12:3.1.1 (early-semver) is selected over 2.5.1
[error] 	    +- org.scanamo:scanamo-zio_2.12:1.0.0-M15+101-13c581a6-SNAPSHOT (depends on 3.1.1)
[error] 	    +- co.fs2:fs2-core_2.12:3.0.3                         (depends on 3.1.1)
[error] 	    +- org.typelevel:cats-effect_2.12:2.5.1               (depends on 2.5.1)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
```
Upgrading to use …

Upgrade to cats-effect v3.1.1, preparing for sbt v1.5

---

build.sbt
cats/src/main/scala/org/scanamo/ops/CatsInterpreter.scala
cats/src/test/scala/org/scanamo/ScanamoCatsSpec.scala
project/build.properties

The changes required by this update are:
* Removing use of the [deprecated sbt-0.13-style-DSL **` in `** syntax](https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#Migrating+to+slash+syntax)
* Tweaks for sbt v1.5 eviction errors (see sbt/sbt#6221):
* Upgrade `cats-effect` to v3.1.1 - see https://github.com/scanamo/scanamo/pull/1166, which should be merged before this PR
* Set `evictionErrorLevel := Level.Info`, because while we can fix `cats-effect`, we can't currently fix `akka-http` - the current latest version of `akka-http` suffers from a semver issue with `scala-java8-compat` - see akka/akka#30375 :
```
[info] 	* org.scala-lang.modules:scala-java8-compat_2.12:1.0.0 (early-semver) is selected over 0.8.0
[info] 	    +- …
```

Upgrade to sbt v1.5

---

.gitignore

Both IntelliJ and Bloop can create a lot of files that aren't meant to be committed to source control, and for new contributors coming to Scanamo, the big list of files they'll see when they come to contribute a commit can be quite intimidating. IntelliJ is a common IDE for Scala developers, even more so amongst [less-experienced devs](https://user-images.githubusercontent.com/52038/125192188-7133c500-e23e-11eb-829c-6b49a5135d9a.jpg).
One possible way of handling this is asking all contributors to add entries to their personal, user-specific, global git settings, which would avoid lengthening the .gitignore file committed within the repo itself. However, if that's the route we want to take, the very minimum we should do is *document this* for new contributors in the `CONTRIBUTING.md` …

gitignore files that new developers will commonly encounter

---

scanamo/src/main/scala/org/scanamo/DynamoFormat.scala

The instance method version of `coercedXmap` on the `DynamoFormat` trait delegates to the static `DynamoFormat.coercedXmap` method - but that requires an implicit `ClassTag` for `T`, the `Throwable` type that it's allowed to coerce:
https://github.com/scanamo/scanamo/blob/4f79e47e1387c98a48120114050853d86c8df0c5/scanamo/src/main/scala/org/scanamo/DynamoFormat.scala#L122-L126
The instance method version of `coercedXmap` can't know what that `Throwable` type is, so far as I can see, with it's current signature?
https://github.com/scanamo/scanamo/blob/4f79e47e1387c98a48120114050853d86c8df0c5/scanamo/src/main/scala/org/scanamo/DynamoFormat.scala#L59-L60
The Scala 3 compiler spots this, and errors with a `No ClassTag available` message:
```
[error] -- Error: …
```

Remove instance-method version of `coercedXmap`

---

build.sbt

With the update to sbt v1.5 in https://github.com/scanamo/scanamo/pull/1167 we realised that the `alpakka` subproject in Scanamo had a semver issue that needed handling. sbt v1.5 treats the eviction problems it encounters more seriously than previous versions of sbt, raising a fatal error rather than a warning, so this blocked the `alpakka` subproject from building - but as it turned out, the error _wasn't_ indicative of a serious incompatibility issue (see https://github.com/akka/akka/pull/30375). Consequently, we just set `evictionErrorLevel := Level.Info` [on the `alpakka` subproject](https://github.com/scanamo/scanamo/pull/1167/files#r672207910) and everything built again.
However, I hadn't taken into account that the `docs` subproject depends on `alpakka`, and when IntelliJ BSP …

Fix `docs/update` sbt task so IntelliJ BSP import succeeds

---

alpakka/src/test/scala/org/scanamo/ScanamoAlpakkaSpec.scala
build.sbt
cats/src/main/scala/org/scanamo/ops/CatsInterpreter.scala
cats/src/test/scala/org/scanamo/ScanamoCatsSpec.scala
scanamo/src/main/scala/org/scanamo/DynamoObject.scala
scanamo/src/main/scala/org/scanamo/ScanamoFree.scala
scanamo/src/main/scala/org/scanamo/ScanamoSync.scala
scanamo/src/main/scala/org/scanamo/ops/ScanamoAsyncInterpreter.scala
scanamo/src/main/scala/org/scanamo/ops/package.scala
scanamo/src/main/scala/org/scanamo/query/ConditionExpression.scala
scanamo/src/main/scala/org/scanamo/query/UniqueKeyCondition.scala
scanamo/src/test/scala-2.x/org/scanamo/ScanamoAsyncTest.scala
scanamo/src/test/scala-2.x/org/scanamo/ScanamoTest.scala
scanamo/src/test/scala-2.x/org/scanamo/TableTest.scala
zio/src/main/scala/org/scanamo/ops/ZioInterpreter.scala
zio/src/test/scala/org/scanamo/ScanamoZioSpec.scala

_Here's a few things to move the codebase closer to compatibility with Scala 3 (without actually activating Scala 3 compilation at this point):_
The [`-Xsource:3`](https://docs.scala-lang.org/scala3/guides/migration/tooling-tour.html#the-scala-213-compiler) flag is an option that's been added to the latest releases of the Scala 2 compiler - it aims to enforce a bit more Scala 3 compatibility in the source code.
* Fix Scala 3.0.0 `E057 Type Mismatch Error` compiler errors in Scanamo interpreter classes with some DRY refactors.
* In Scala 3, defining implicits requires a type declaration. Once you have that type declared, you can also sometimes use a more-compact [SAM](https://www.scala-lang.org/news/2.12.0/#lambda-syntax-for-sam-types) declaration.
* String concatenation with `+` is …

Preparatory work for Scala 3, set `-Xsource:3` scalac flag

---

build.sbt
cats/src/main/scala/org/scanamo/ScanamoCats.scala
cats/src/test/scala/org/scanamo/ScanamoCatsSpec.scala

This change updates to the latest version of `fs2-core`, which is now compatible with `cats-effect` v3.1.1 (introduced in
https://github.com/scanamo/scanamo/pull/1166). Unfortunately there's not yet a version of `monix` that supports `cats-effect` v3.1.1, so we're dropping support for Monix for now - the actual implementation code within Scanamo for the Monix support is only 4 lines, so can probably be easily copied into an end-user project if it's needed!
Sbt is capable of warning us about version conflicts in dependencies, but gave no warning of the `cats-effect` version conflict, I think because the `fs2-core` & `monix` dependencies were marked as already `Provided`. My guess as to why the `Provided` marker was used is that the `scanamo-cats-effect` artifact gave support for both …

Fix #1184 (`cats-effect` version conflict) by dropping Monix for now

---

build.sbt
scanamo/src/main/scala-2.x/org/scanamo/generic/AutoDerivation.scala
scanamo/src/main/scala-2.x/org/scanamo/generic/Derivation.scala
scanamo/src/main/scala-2.x/org/scanamo/generic/SemiautoDerivation.scala

Only the most recent releases of the Magnolia library are available for both Scala 2 and 3 - this is since the project maintainership moved to the https://github.com/softwaremill organisation. Note that as part of this move, there's an updated group id, and package name of `magnolia1` - some details about that here: https://github.com/softwaremill/magnolia/issues/327

Scala 3 prep: Upgrade to magnolia 1.0

---

docs/docs/conditional-operations.md
docs/docs/filters.md
docs/docs/index.md
docs/docs/operations.md

Internal docs links are pointing to the source filename rather than the generated page

Fix 404ing docs links

---

build.sbt

With PRs https://github.com/scanamo/scanamo/pull/1167 (upgrading to sbt v1.5) & https://github.com/scanamo/scanamo/pull/1176 we made _all_ of sbt's new eviction errors non-fatal, but it turns that wasn't necessary - we can just compensate specifically for the problematic `scala-java8-compat` dependency with a `libraryDependencySchemes` setting, which _won't_ disable eviction errors for all other dependencies.
Many thanks to @ennru for finding that out and [passing it](https://github.com/akka/alpakka/pull/2688#issuecomment-981676632) on! Now I look closer at the sbt v1.5.0 release notes, I see this [was mentioned](https://github.com/sbt/sbt/releases/tag/v1.5.0#:~:text=If%20the%20user,effect%22%20%25%20VersionScheme.Always), I just missed it I guess :disappointed: .

Reinstate fatal severity of sbt eviction errors

---

.travis.yml

I believe Jekyll does not require this Gem as of v4.0.0.
This is unrelated to the Travis build currently failing due to https://www.moncefbelyamani.com/how-to-fix-undefined-local-variable-or-method-d-for-gem-specification-class/ - I've fixed that by deleting the Travis cache

Remove Ruby Sass

---

scanamo/src/main/scala/org/scanamo/ScanamoFree.scala
scanamo/src/main/scala/org/scanamo/SecondaryIndex.scala
scanamo/src/main/scala/org/scanamo/Table.scala
scanamo/src/test/scala-2.x/org/scanamo/SecondaryIndexTest.scala
scanamo/src/test/scala-2.x/org/scanamo/TableTest.scala

`Table` has provides `scan0` and `query0` to access the raw response, for which a common use-case is to access the last evaluated (ie paging) key. `SecondaryIndex` lacks these methods, making it impossible to page indexes. Per #1324, this slimmed-down PR adds those methods so that paged queries are at least possible on indexes. However the larger issue around paging indexes (ie, the impossibility to safely form a complete index paging key in common use-cases) still stands. This PR is at least a workaround until the larger issue can be addressed.

Add SecondaryIndex methods exposing raw response

---

.github/workflows/ci.yaml

This PR fixes release workflow error.
Release job for snapshot repository always faied as seen in https://github.com/scanamo/scanamo/pull/1577, which is (probably) because no credentials is found for new s01.oss.sonatype.org repository.

Run release job only when tag is pushed

---

scanamo/src/main/scala/org/scanamo/DynamoResultStream.scala

The NPE occurs when scannedCount underlying field is null. Simple map on Option doesn't help as apparently there's implicit cast from Java Integer  to Scala Int happening and it would still fail with NPE, therefore chain of flatMaps.
It would be great if merge of this PR would result in new build published to Maven. Thanks in advance!

Fix NPE in DynamoResultStream

---

cats/src/main/scala/org/scanamo/ops/CatsInterpreter.scala
scanamo/src/main/scala/org/scanamo/DynamoReadError.scala
scanamo/src/main/scala/org/scanamo/ScanamoFree.scala
scanamo/src/main/scala/org/scanamo/Table.scala
scanamo/src/main/scala/org/scanamo/TransactionalWriteAction.scala
scanamo/src/main/scala/org/scanamo/ops/ScanamoOpsA.scala
scanamo/src/main/scala/org/scanamo/ops/ScanamoSyncInterpreter.scala
scanamo/src/main/scala/org/scanamo/ops/package.scala
scanamo/src/main/scala/org/scanamo/request/ScanamoRequest.scala
scanamo/src/test/scala/org/scanamo/ScanamoAsyncTest.scala
scanamo/src/test/scala/org/scanamo/ScanamoTest.scala
zio/src/main/scala/org/scanamo/ops/ZioInterpreter.scala

This PR provides support for multi-action write requests (as detailed in the Dynamo spec [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transaction-apis.html))
Currently the Scanamo API allows only write requests of the same type (Put, Update, Delete) to be grouped together in a single transaction (i.e. `transactPutAll`, `transactUpdateAll`, `transactDeleteAll`).
This change introduces `transactionWrite` which accepts multiple TransactionWriteActions. These actions could be a mix of `Put`, `Update`, `Delete` or `ConditionCheck` types and can span multiple tables.

Add support for multi-action write transactions

---

scanamo/src/main/scala/org/scanamo/SecondaryIndex.scala
scanamo/src/main/scala/org/scanamo/Table.scala

Solves: https://github.com/scanamo/scanamo/issues/1638

Add primitive exclusive start key support to Table and SecondaryIndex

---

.github/workflows/ci.yml
.github/workflows/release.yml
CONTRIBUTING.md
build.sbt
project/plugins.sbt
version.sbt

As mentioned in https://github.com/scanamo/scanamo/issues/1763, we're switching to use `gha-scala-library-release-workflow` for releasing the Scanamo to Maven Central. This is a change from the release process based on `sbt-ci-release` that was introduced with https://github.com/scanamo/scanamo/pull/280 - it used to be that to trigger a release, we would push a git tag with a manually-selected version number (eg `v1.0.3`), the new process is now to run the `Release` workflow manually, which will automatically determine a version number based on the version-compatibility checks performed by `sbt-version-policy`.
In order to do this, we've had to follow the one-off organisation-setup steps in:
https://github.com/guardian/gha-scala-library-release-workflow/blob/main/docs/org-setup.md …

Adopt GHA Scala Library Release Workflow

---

cats/src/main/scala/org/scanamo/ScanamoCats.scala
pekko/src/main/scala/org/scanamo/ScanamoPekko.scala
pekko/src/main/scala/org/scanamo/ops/PekkoInterpreter.scala
scanamo/src/main/scala/org/scanamo/ScanamoAsync.scala
scanamo/src/main/scala/org/scanamo/ScanamoClient.scala
scanamo/src/main/scala/org/scanamo/ScanamoSync.scala
scanamo/src/test/scala/org/scanamo/TableTest.scala
zio/src/main/scala/org/scanamo/ScanamoZio.scala

The 5 Scanamo client objects (`Scanamo`, `ScanamoAsync` `CatsScanamo`, `ZioScanamo`, `PekkoScanamo`) all have common `exec` & `execT` methods with almost completely identical implementations. This change introduces a new common `ScanamoClient` super-class for all 5 client objects that implements those methods.
Result: less code! ✨ 
I was tempted to remove the 5 subtype instance classes altogether, as there's not much need for them from the Scanamo implementation side - we could get by with just the 5 singleton objects providing `apply()` methods to construct `ScanamoClient` instances - but there are some wrinkles with that:
* Existing code in consumers of the Scanamo library will typically hand around instance references with the type of the subtype (ie `scanamo: ScanamoAsync`) - they've …

Extract common `exec` & `execT` methods into new `ScanamoClient`

---

pekko/src/main/scala/org/scanamo/ops/PekkoInterpreter.scala
scanamo/src/main/scala/org/scanamo/ScanamoFree.scala
scanamo/src/main/scala/org/scanamo/Table.scala
scanamo/src/main/scala/org/scanamo/ops/AsyncFrameworks.scala
scanamo/src/main/scala/org/scanamo/ops/ScanamoOpsA.scala
scanamo/src/main/scala/org/scanamo/ops/ScanamoSyncInterpreter.scala
scanamo/src/test/scala/org/scanamo/ScanamoTest.scala

This is based on the 2nd of the 2 distinct changes proposed in PR https://github.com/scanamo/scanamo/pull/1776, which I'm now separating out into 2 PRs (this will now be the *1st* to be merged). Luciano Preissler's original description for _this_ change in https://github.com/scanamo/scanamo/pull/1776 was:
> Exposes TransactionCanceledException:
> This enhancement strengthens error handling capabilities, enabling users
> to distinguish between different transaction cancellation scenarios, thereby
> facilitating improved troubleshooting and error resolution.
This change exposes `TransactionCanceledException` by changing the result type of _transaction_ operations to `Either[TransactionCanceledException, TransactWriteItemsResponse]`, rather than just simply `TransactWriteItemsResponse`.
This …

Improve transaction error-handling capabilities

---

scanamo/src/main/scala/org/scanamo/DynamoObject.scala
scanamo/src/main/scala/org/scanamo/ScanamoFree.scala
scanamo/src/main/scala/org/scanamo/ops/package.scala
scanamo/src/main/scala/org/scanamo/query/ConditionExpression.scala
scanamo/src/main/scala/org/scanamo/query/QueryableKeyCondition.scala
scanamo/src/main/scala/org/scanamo/request/AttributeNamesAndValues.scala
scanamo/src/main/scala/org/scanamo/request/ScanamoRequest.scala
scanamo/src/main/scala/org/scanamo/update/UpdateAndCondition.scala
scanamo/src/main/scala/org/scanamo/update/UpdateExpression.scala
scanamo/src/test/scala/org/scanamo/request/RequestConditionTest.scala
scanamo/src/test/scala/org/scanamo/update/UpdateExpressionTest.scala

* **`RequestCondition` dynamo values become non-optional**: instead they can just be `DynamoObject.empty`
* **New class `AttributeNamesAndValues`**: we often combine the different sources of attribute names/values in a request (eg, 'update' and 'condition') and there's no point in repeatedly writing code where names are combined, and then _values_ are combined - we always want to aggregate both at the same time, now supported with `AttributeNamesAndValues`
* **New class `UpdateAndCondition`**: combines `UpdateExpression` & `Option[Condition]` - models the payload of both normal `UpdateItem` & transactional `Update` requests.
* Using the [lambda syntax for Single Abstract Method (SAM) types](https://www.scala-lang.org/news/2.12.0/#lambda-syntax-for-sam-types) in the implementation of many …

Simplify processing of `RequestCondition` attribute values - make them non-optional

---

scanamo/src/main/scala/org/scanamo/ops/package.scala
scanamo/src/main/scala/org/scanamo/update/UpdateExpression.scala
scanamo/src/test/scala/org/scanamo/TableTest.scala

This change makes list-appending support for `Update`s embedded in *transactions* consistent with the support in normal `UpdateItemRequest`s.
The injection of the necessary `:emptyList` attribute has moved from `update(req: ScanamoUpdateRequest): UpdateItemRequest` into the code of `UpdateExpression`, where it can be used for both transactional and non-transactional code.
DynamoDB update operations let you append to existing list attributes with the [`list_append()`](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET.UpdatingListElements) function - however, if you're attempting to execute an update-append on an attribute that is not yet populated (eg the item does not even _exist_ yet), DynamoDB will …

Add list-appending support to transactional `Update`s

---

scanamo/src/main/scala/org/scanamo/ScanamoFree.scala
scanamo/src/main/scala/org/scanamo/internal/aws/sdkv2/package.scala
scanamo/src/main/scala/org/scanamo/ops/package.scala

Scanamo's own Scala-based models of DynamoDB requests use [Scala's idiomatic approach to optional values](https://alvinalexander.com/scala/using-scala-option-some-none-idiom-function-java-null/) - use `Option` - but this repeatedly gives us a fiddly job when coping with the [fluent nature of the AWS SDK for Java](https://aws.amazon.com/blogs/developer/fluent-client-builders/), which chains methods on builders. We want to pretend that the builders aren't mutable (because if they were written in Scala, they wouldn't be mutable), and using the default methods on Option, the most concise way to do that for a builder is using `optionValue.foldLeft(builder)(builder.setter)` - which is _reasonably_ concise, but you'll notice that we're repeating `builder` twice, and it's not possible to chain …

Extend AWS SDK builders to ease `Option`-setting

---

.github/workflows/ci.yml
build.sbt
pekko/src/main/scala/org/scanamo/ScanamoPekko.scala
pekko/src/test/scala/org/scanamo/ScanamoPekkoSpec.scala

Scala 3 support was added to Scanamo with https://github.com/scanamo/scanamo/pull/1577 / https://github.com/scanamo/scanamo/pull/1596 in November 2022, but as mentioned in that 2nd PR, we only enabled Scala 3 support for Scanamo subprojects where it was nice & easy to do so - amongst others, that excluded Alpakka (the predecessor to Pekko, originally added to Scanamo with https://github.com/scanamo/scanamo/pull/151 in October 2017).
When Pekko was added to Scanamo (porting the Alpakka support) with https://github.com/scanamo/scanamo/pull/1660 in September 2023, it retained the constraint of not supporting Scala 3 - we're fixing that here.
* Scala 3 cross-compilation enabled for the Pekko project
* Pekko tests enabled under the Scala 3 CI builds
* [Fixed compilation error in …

Pekko: Support Scala 3

---

.github/workflows/ci.yml
build.sbt
zio/src/main/scala/org/scanamo/ScanamoZio.scala
zio/src/test/scala/org/scanamo/ScanamoZioSpec.scala

_This is very similar to PR https://github.com/scanamo/scanamo/pull/1805, which added Scala 3 support to Scanamo's **Pekko** subproject._
Scala 3 support was added to Scanamo with https://github.com/scanamo/scanamo/pull/1577 / https://github.com/scanamo/scanamo/pull/1596 in November 2022, but as mentioned in that 2nd PR, we only enabled Scala 3 support for Scanamo subprojects where it was nice & easy to do so - amongst others, that excluded ZIO (originally added to Scanamo with https://github.com/scanamo/scanamo/pull/262 in October 2018).
* Scala 3 cross-compilation enabled for the ZIO project
* ZIO tests enabled under the Scala 3 CI builds
* [Fixed compilation error in `ScanamoZio`](https://github.com/scanamo/scanamo/pull/1806#discussion_r1733285974) relating to Scala 3's syntax for …

ZIO: Support Scala 3

---

.github/workflows/ci.yml

https://github.com/actions/runner-images/issues/10636 removed `sbt` from the `ubuntu-latest` image - hence the need for https://github.com/sbt/setup-sbt - or, as we use at the Guardian,  https://github.com/guardian/setup-scala which combines [`setup-java`](https://github.com/actions/setup-java) & [`setup-sbt`](https://github.com/sbt/setup-sbt) with good defaults for us.
To use `guardian/setup-scala` with Scanamo, I needed to update it with this PR to support the way the Scanamo CI build uses GitHub runner matrix to vary the `java` version:
* https://github.com/guardian/setup-scala/pull/1

Use `guardian/setup-scala` to cope with Ubuntu changes
