scanamo/scanamo

- README.md
- src/main/scala/com/gu/scanamo/DynamoKeyCondition.scala
- src/main/scala/com/gu/scanamo/QueryableKeyCondition.scala
- src/main/scala/com/gu/scanamo/Scanamo.scala
- src/main/scala/com/gu/scanamo/ScanamoRequest.scala
- src/main/scala/com/gu/scanamo/UniqueKeyCondition.scala
- src/main/scala/com/gu/scanamo/package.scala
- src/test/scala/com/gu/scanamo/ScanamoTest.scala
Also supports queries which are not just exact matches, e.g. `<` and `beginsWith` and gets rid of some unnecessary type parameters.
I like the consistency of the interface, but I'm less keen on the amount of implicit machinery involved.
> Support multiple key get, delete, query, etc.

- src/main/scala/com/gu/scanamo/DynamoResultStream.scala
- src/main/scala/com/gu/scanamo/Scanamo.scala
- src/main/scala/com/gu/scanamo/ScanamoAsync.scala
- src/main/scala/com/gu/scanamo/ScanamoFree.scala
Streaming is disappearing from Cats, so revert to just using collection.immutable.Stream
> Change `Streaming` to `Stream`

- build.sbt
> remove discipline dependency

- README.md
- build.sbt
- src/main/scala/com/gu/scanamo/Table.scala
- src/main/scala/com/gu/scanamo/package.scala
This aim is for this to be the main way of using Scanamo. That does rely on people being comfortable with using the `Free` type.
cc @adamnfish
> Add a Table type

- src/main/scala/com/gu/scanamo/DynamoFormat.scala
This adds some implicit formats for
* `Set[Int]`, `Set[Long]`, and `Set[Double]` (using `getNS`/`withNS`) 
* `Set[String]` (using `getSS`/`withSS`)
Not sure if there's a better way to make the `Set` implicits be more generic, since sets only exist for numbers and strings (rather than `AttributeValue`s)
> Add implicit DynamoFormat for Double and Set

- src/main/scala/com/gu/scanamo/DynamoFormat.scala
Also made javaListFormat public as it was requested and I don't see a good reason for keeping it private.
Fixes #26
> Add format for Vector

- src/main/scala/com/gu/scanamo/ScanamoFree.scala
- src/main/scala/com/gu/scanamo/ScanamoRequest.scala
- src/main/scala/com/gu/scanamo/Table.scala
- src/main/scala/com/gu/scanamo/ops/ScanamoOpsA.scala
- src/main/scala/com/gu/scanamo/query/ConditionExpression.scala
- src/main/scala/com/gu/scanamo/request/ScanamoRequest.scala
- src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala
Along with #31, this fixes #22
> Add support for conditional deletes

- build.sbt
- src/main/scala/com/gu/scanamo/DynamoResultStream.scala
- src/main/scala/com/gu/scanamo/Scanamo.scala
- src/main/scala/com/gu/scanamo/ScanamoAsync.scala
- src/main/scala/com/gu/scanamo/ScanamoFree.scala
- src/main/scala/com/gu/scanamo/Table.scala
- src/test/scala/com/gu/scanamo/LocalDynamoDB.scala
- src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala
- src/test/scala/com/gu/scanamo/ScanamoFreeTest.scala
> Support limiting the results coming back from a query

- CHANGES.md
- README.md
Add changes for hopefully imminent 0.5.0 release and attempts to improve the structure of the README including an example of using indexes, as requested in #30
> 0.5.0 release docs

- src/main/scala/com/gu/scanamo/DynamoFormat.scala
- src/main/scala/com/gu/scanamo/Scanamo.scala
- src/main/scala/com/gu/scanamo/ScanamoAsync.scala
- src/main/scala/com/gu/scanamo/ScanamoFree.scala
- src/main/scala/com/gu/scanamo/ScanamoRequest.scala
- src/main/scala/com/gu/scanamo/Table.scala
- src/main/scala/com/gu/scanamo/error/DynamoReadError.scala
- src/main/scala/com/gu/scanamo/ops/ScanamoOpsA.scala
- src/main/scala/com/gu/scanamo/package.scala
- src/main/scala/com/gu/scanamo/query/ConditionExpression.scala
- src/main/scala/com/gu/scanamo/request/ScanamoRequest.scala
- src/main/scala/com/gu/scanamo/update/UpdateExpression.scala
- src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala
- src/test/scala/com/gu/scanamo/ScanamoFreeTest.scala
Work still outstanding includes
> Support Update SET operations

- .travis.yml
- build.sbt
Still for a little while longer the default for Spark.
> Add support for Scala 2.10

- README.md
- src/main/scala/com/gu/scanamo/Table.scala
Also added a bit more structure
> Added documentation on Update to the README

- src/main/scala/com/gu/scanamo/Scanamo.scala
- src/main/scala/com/gu/scanamo/ScanamoAsync.scala
- src/main/scala/com/gu/scanamo/ScanamoFree.scala
- src/main/scala/com/gu/scanamo/Table.scala
- src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala
Proposal for batch deleteAll
- resolves item #27
> batch deleteAll

- .travis.yml
- README.md
- build.sbt
- project/plugins.sbt
- src/main/resources/microsite/data/menu.yml
- src/main/tut/asynchronous.md
- src/main/tut/batch-operations.md
- src/main/tut/custom-formats.md
- src/main/tut/index.md
- src/main/tut/put-get.md
- src/main/tut/querying.md
- src/main/tut/scanning.md
- src/main/tut/updating.md
- src/main/tut/using-indexes.md
https://guardian.github.io/scanamo/
> Add prettier docs using sbt-microsite

- src/main/scala/com/gu/scanamo/DerivedDynamoFormat.scala
See https://github.com/guardian/scanamo/issues/76
> Delete 'more helpful' errors, as they can be confusing

- .travis.yml
- src/main/scala/com/gu/scanamo/Table.scala
- src/main/scala/com/gu/scanamo/package.scala
- src/main/scala/com/gu/scanamo/update/UpdateExpression.scala
This is designed to address #88
> Allow nested attributes to be updated

- src/main/resources/microsite/data/menu.yml
- src/main/tut/asynchronous.md
- src/main/tut/conditional-operations.md
- src/main/tut/dynamo-format.md
- src/main/tut/operations.md
- src/main/tut/using-indexes.md
> Document conditional operations

- src/main/scala/com/gu/scanamo/DerivedDynamoFormat.scala
- src/main/scala/com/gu/scanamo/DynamoFormat.scala
- src/main/scala/com/gu/scanamo/EnumerationDynamoFormat.scala
- src/main/scala/com/gu/scanamo/Table.scala
- src/main/scala/com/gu/scanamo/ops/ScanamoInterpreters.scala
- src/main/scala/com/gu/scanamo/package.scala
- src/main/scala/com/gu/scanamo/update/UpdateExpression.scala
> Support updating one attribute to the value of another

- src/main/scala/com/gu/scanamo/package.scala
- src/main/scala/com/gu/scanamo/query/ConditionExpression.scala
- src/main/scala/com/gu/scanamo/query/DynamoKeyCondition.scala
- src/main/scala/com/gu/scanamo/query/QueryableKeyCondition.scala
- src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala
* Added `Between` `RangeKeyCondition`
* Added `betweenCondition` `ConditionExpression`
* Added some DSL so you can do stuff like `'mode -> "Underground" and ('zone between (2 and 4))`
> #104 implement 'between'

- README.md
Given that there's a decent amount of documentation on the site now, I'd like to slim down the README to a more minimal structure with just one simple example.
I'd be very interested in any and all feedback on whether this seems sensible.
> Minimal docs in README, pointing at site instead

- src/main/scala/com/gu/scanamo/package.scala
- src/main/scala/com/gu/scanamo/query/ConditionExpression.scala
- src/main/scala/com/gu/scanamo/query/DynamoKeyCondition.scala
- src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala
https://github.com/guardian/scanamo/issues/109
> Add "attribute_not_exists" condition expression

- src/main/scala/com/gu/scanamo/ScanamoFree.scala
- src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala
Although it can be improved, this fixes the DynamoDB batch get size limitation of 100 items per request.
> #103 Automatically managing batching for getAll

- build.sbt
- project/plugins.sbt
- src/main/scala/com/gu/scanamo/DynamoResultStream.scala
- src/main/scala/com/gu/scanamo/EnumerationDynamoFormat.scala
- src/main/scala/com/gu/scanamo/Scanamo.scala
- src/main/scala/com/gu/scanamo/error/DynamoReadError.scala
- src/main/scala/com/gu/scanamo/query/DynamoKeyCondition.scala
- src/main/scala/com/gu/scanamo/query/UniqueKeyCondition.scala
- src/main/scala/com/gu/scanamo/request/ScanamoRequest.scala
- src/test/scala/com/gu/scanamo/ScanamoFreeTest.scala
- src/test/scala/com/gu/scanamo/ScanamoTest.scala
Note that 2.12.2 introduced unused warnings by default when linting
> Upgrade to Scala 2.12.3 plus various dependencies

- alpakka/src/main/scala/com/gu/scanamo/ScanamoAlpakka.scala
- alpakka/src/test/scala/com/gu/scanamo/ScanamoAlpakkaSpec.scala
- scanamo/src/main/scala/com/gu/scanamo/Scanamo.scala
- scanamo/src/main/scala/com/gu/scanamo/ScanamoAsync.scala
- scanamo/src/main/scala/com/gu/scanamo/ScanamoFree.scala
- scanamo/src/main/scala/com/gu/scanamo/Table.scala
- scanamo/src/main/scala/com/gu/scanamo/ops/ScanamoInterpreters.scala
- scanamo/src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala
> Return overwriting item as put operation result

- scanamo/src/main/scala/com/gu/scanamo/Table.scala
- scanamo/src/main/scala/com/gu/scanamo/query/ConditionExpression.scala
> Allow `Condition` as a parameter to `Condition.or/and`

- scanamo/src/main/scala/com/gu/scanamo/Table.scala
- scanamo/src/main/scala/com/gu/scanamo/package.scala
- scanamo/src/main/scala/com/gu/scanamo/query/AttributeName.scala
- scanamo/src/main/scala/com/gu/scanamo/query/ConditionExpression.scala
- scanamo/src/main/scala/com/gu/scanamo/query/DynamoKeyCondition.scala
- scanamo/src/main/scala/com/gu/scanamo/query/QueryableKeyCondition.scala
- scanamo/src/main/scala/com/gu/scanamo/update/UpdateExpression.scala
This fixes https://github.com/guardian/scanamo/issues/136
As a nice bonus this harmonises the way we treat attribute names in
updates and conditions
> Add support for conditions on nested attribute names

- formats/src/main/scala/com/gu/scanamo/DynamoFormat.scala
What does this PR do?
- Adds support for BigDecimal type
> DynamoDB BigDecimal Type Support

- .travis.yml
- README.md
- build.sbt
> Reflect the move from `guardian` to `scanamo` Github organisation

- docs/src/main/tut/CNAME
- docs/src/main/tut/asynchronous.md
- project/build.properties
- project/plugins.sbt
Every time the docs are published the CNAME gets destroyed and `www.scanamo.org` stops resolving. Hopefully this will stop that happening.
> Microsite CNAME

- scanamo/src/main/scala/com/gu/scanamo/Table.scala
- scanamo/src/main/scala/com/gu/scanamo/query/ConditionExpression.scala
Addresses #224 
I've just fallen victim of an N+1 query, that was killing the performance of my lambda. Using the `IN` operator reduces running time by two orders of magnitude.
> Add support for IN operator

- build.sbt
- cats/src/test/scala/com/gu/scanamo/ScanamoCatsSpec.scala
Created off [Phil's](https://github.com/scanamo/scanamo/pull/228) as his computer is broken and am unable to pull his branch.
> Aggregate cats interpreter into root project

- build.sbt
- scalaz-zio/src/main/scala/com/gu/scanamo/ScanamoZio.scala
- scalaz-zio/src/main/scala/com/gu/scanamo/ops/ZioInterpreter.scala
- scalaz-zio/src/test/scala/com/gu/scanamo/ScanamoZioSpec.scala
An itch I've wanted to scratch for a long time. I did not add all the deprecated functions to `ScanamoZio` because, well, deprecated.
> Add ZIO interpreter

- CHANGES.md
I listed most of the changes, but I'm really terrible at that so I hope I've not missed anything.
cc @Slakah
> Pre M8 release

- formats/src/main/scala/com/gu/scanamo/DynamoFormat.scala
Addressing issue: https://github.com/scanamo/scanamo/issues/249
> Add missing floatFormat and floatSetFormat to DynamoFormat

- .scala-steward.conf
I think they've proven enough to be a major pain in the a**
> Ignore updates for the dynamo db sdk

- java-time/src/main/scala/org/scanamo/time/JavaTimeFormats.scala
- java-time/src/test/scala/org/scanamo/time/TimeGenerators.scala
> Add ZoneDateTime generator

- alpakka/src/main/scala/org/scanamo/ScanamoAlpakka.scala
Hi @regiskuckaertz 
Do you think returning a Future from exec will be idiomatic? If yes, raised a PR for this addition :)
> Added overloaded exec to return Future

- formats/src/main/scala/org/scanamo/DynamoObject.scala
- formats/src/test/scala/org/scanamo/DynamoFormatTest.scala
> Do not encode empty maps as null attribute values

- formats/src/main/scala/org/scanamo/DynamoDefault.scala
- formats/src/main/scala/org/scanamo/DynamoFormat.scala
- formats/src/test/scala/org/scanamo/DynamoFormatSpec.scala
- java-time/src/main/scala/org/scanamo/time/JavaTimeFormats.scala
- joda/src/main/scala/org/scanamo/joda/JodaFormats.scala
> Add ability to override default in `*xmap`

- formats/src/main/scala/org/scanamo/DynamoArray.scala
- formats/src/test/scala/org/scanamo/DynamoFormatTest.scala
As discussed with @regiskuckaertz.
A quick observation as a first-time contributor: it might be good to [configure the local Dynamo instance](https://github.com/localytics/sbt-dynamodb#configuration) to automatically launch and terminate when running tests.
> Fix NULLs when writing empty lists

- docs/src/main/tut/index.md
> Fix package name and version for scanamo.org index page

- build.sbt
- formats/src/main/scala/org/scanamo/DynamoFormat.scala
- scanamo/src/main/scala/org/scanamo/Table.scala
- scanamo/src/main/scala/org/scanamo/query/ConditionExpression.scala
- scanamo/src/main/scala/org/scanamo/query/QueryableKeyCondition.scala
- scanamo/src/main/scala/org/scanamo/query/UniqueKeyCondition.scala
One set of macros we can do without
> Remove simulacrum

- project/metals.sbt
I would prefer to move this into `~/.sbt` but it doesn't work 😞
> Bloopery stuff

- alpakka/src/main/scala/org/scanamo/ops/AlpakkaInterpreter.scala
- alpakka/src/test/scala/org/scanamo/ScanamoAlpakkaSpec.scala
- cats/src/main/scala/org/scanamo/ops/CatsInterpreter.scala
- cats/src/test/scala/org/scanamo/ScanamoCatsSpec.scala
- scanamo/src/main/scala/org/scanamo/ScanamoFree.scala
- scanamo/src/main/scala/org/scanamo/Table.scala
- scanamo/src/main/scala/org/scanamo/ops/ScanamoAsyncInterpreter.scala
- scanamo/src/main/scala/org/scanamo/ops/ScanamoOpsA.scala
- scanamo/src/main/scala/org/scanamo/ops/ScanamoSyncInterpreter.scala
- scanamo/src/main/scala/org/scanamo/ops/package.scala
- scanamo/src/main/scala/org/scanamo/request/ScanamoRequest.scala
- scanamo/src/test/scala/org/scanamo/ScanamoAsyncTest.scala
- scanamo/src/test/scala/org/scanamo/ScanamoFreeTest.scala
- scanamo/src/test/scala/org/scanamo/ScanamoTest.scala
- testkit/src/main/scala/org/scanamo/LocalDynamoDB.scala
- zio/src/main/scala/org/scanamo/ops/ZioInterpreter.scala
- zio/src/test/scala/org/scanamo/ScanamoZioSpec.scala
Introduces the ability to action transactional updates/deletes.
> Introduce transactional (update & delete) methods

- build.sbt
- zio/src/test/scala/org/scanamo/ScanamoZioSpec.scala
> Update zio version to "1.0.0-RC18-2"

- .travis.yml
- build.sbt
> Build speedup

- scanamo/src/main/scala/org/scanamo/ops/package.scala
- scanamo/src/test/scala-2.x/org/scanamo/ScanamoTest.scala
DeleteReturn was being ignored, this adds it to the dynamodb request to resolve #879
> Fix bug in deleteAndReturn

- alpakka/src/test/scala/org/scanamo/ScanamoAlpakkaSpec.scala
- scanamo/src/main/scala/org/scanamo/package.scala
- scanamo/src/main/scala/org/scanamo/update/UpdateExpression.scala
- scanamo/src/test/scala-2.x/org/scanamo/ScanamoTest.scala
- scanamo/src/test/scala/org/scanamo/update/UpdateExpressionTest.scala
- zio/src/test/scala/org/scanamo/ScanamoZioSpec.scala
Hi there, this PR adds support for the `SET path = if_not_exists(path, :value)` update expression as `UpdateExpression#setIfNotExists`
> Added set if_not_exists update expression

- alpakka/src/main/scala/org/scanamo/ops/AlpakkaInterpreter.scala
- scanamo/src/main/scala/org/scanamo/ops/ScanamoAsyncInterpreter.scala
Thanks a lot Java!
Why doesn't `toScala` do this? :cry:
> Unwrap CompletionException

- scanamo/src/main/scala/org/scanamo/DynamoFormat.scala
Addresses https://github.com/scanamo/scanamo/issues/968
> Support empty string attributes

- docs/docs/dynamo-format.md
- docs/docs/index.md
Scanamo has moved to the org.scanamo organisation.
> Remove references to com.gu

- scanamo/src/main/scala/org/scanamo/DynamoResultStream.scala
Dynamodb applies the `limit` parameter before the FilterExpression is evaluated, so it represents the maximum number of items that will be read, the actual number of items returned may be lower.
```
A single Scan operation reads up to the maximum number of items set (if using the Limit parameter) 
or a maximum of 1 MB of data and then apply any filtering to the results using FilterExpression. If 
LastEvaluatedKey is present in the response, you need to paginate the result set. For more 
information, see Paginating the Results in the Amazon DynamoDB Developer Guide.
```
(https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html)
When paginating with a limit parameter, we need to reduce the limit with each request so that the total number of items read corresponds to the …
> Reduce limit based on scannedCount not returned results

- CONTRIBUTING.md
I generally don't use Scalafmt myself, and we probably shouldn't assume knowledge for new contributors, so it's nice to have some reminders of how to do this! With CI broken https://github.com/scanamo/scanamo/pull/1346 missed making these checks.
> Tell contributors how to run use Scalafmt

- testkit/src/main/scala/org/scanamo/LocalDynamoDB.scala
Adds LocalDynamoDB methods for creating tables with multiple indexes.
Note: I tried to keep the method signatures consistent, but feel free to suggest something else.
> feat(testkit): add LocalDynamoDB methods for creating multi-index tables

- cats/src/main/scala/org/scanamo/ops/CatsInterpreter.scala
related to https://github.com/typelevel/cats-effect/releases/tag/v3.5.0
> cats interpreter should return a finaliser. v3.5.0 changed the  Cancelation Semantics

- build.sbt
- pekko/src/main/scala/org/scanamo/ScanamoPekko.scala
- pekko/src/main/scala/org/scanamo/ops/PekkoInterpreter.scala
- pekko/src/test/scala/org/scanamo/ScanamoPekkoSpec.scala
Fixes https://github.com/scanamo/scanamo/issues/1655
> Add Pekko integration module

- cats/src/main/scala/org/scanamo/ops/CatsAdapter.scala
The original implementation of the code to expose the `ConditionalCheckFailedException` was introduced with PR #212 in May 2018, but I'm not sure why the multi-line implementation was necessary - there's a discussion in PR #212, but I don't quite follow it: https://github.com/scanamo/scanamo/pull/212#discussion_r187699312
The Cats `recover` functionality I'm using here was added with `ApplicativeError` in https://github.com/typelevel/cats/pull/812 in January 2016, so it would have been available for PR #212. Perhaps it was some consequence of us being on AWS SDK v1 at that point, and having to use `AsyncHandler`?
This implementation is definitely much more similar to ones we've used elsewhere, ie `ScalaFutureAdapter` and `PekkoInterpreter`. …
> Simplify `CatsAdapter` exception-handling

- README.md
As part of debug for https://github.com/scalacenter/scaladex/issues/1445 (see https://github.com/scalacenter/scaladex/issues/1445#issuecomment-2582661763), I'm documenting that I'm the owner of scanamo/scanamo.
> Document that @rtyley is the maintainer
